# Generated by Django 6.0.2 on 2026-02-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
                ('Cpassword', models.CharField(max_length=20)),
                ('Profile', models.ImageField(null=True, upload_to='')),
                ('Audio', models.FileField(upload_to='audio')),
                ('Video', models.FileField(upload_to='video')),
                ('Resume', models.FileField(upload_to='document')),
                ('Qualification', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=50)),
            ],
        ),
    ]
