# Generated by Django 6.0.2 on 2026-03-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep_n', models.CharField(max_length=30)),
                ('Dep_d', models.CharField(max_length=100)),
                ('Dep_h', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Image', models.ImageField(null=True, upload_to='image')),
                ('Code', models.CharField(max_length=50)),
                ('Dept', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmpQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Dept', models.CharField(max_length=40)),
                ('Query', models.TextField()),
                ('Status', models.CharField(default='pending')),
                ('Reply', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_desc', models.CharField(max_length=50)),
                ('item_price', models.CharField(max_length=50)),
                ('item_image', models.ImageField(upload_to='')),
                ('item_color', models.CharField(max_length=30)),
                ('item_categery', models.CharField(max_length=50)),
                ('item_quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
